### ISSUE TITLE
R2RMLTermMap.isBlankNode erroneous test

### ISSUE THREAD

**Issue by frmichel** [oeg-upm/morph-rdb#10]
Hi Freddy,

A small bug that probably nobody has seen so far as it concerns blank nodes:
def isBlankNode(): Boolean = {
      Constants.R2RML_BLANKNODE_URI.equals(this.termType)
}

this.termType is an option, so it should be 
      Constants.R2RML_BLANKNODE_URI.equals(this.termType.get)
Otherwise the test always returns false.

In morph-rdb this method is never used anyway... so probably the method can even be removed?

Franck.

**Comment by dachafra** [comment]
@jatoledo please remove the method and close the issue

**Comment by jatoledo** [comment]
Tested and removed
