### ISSUE TITLE
link to R2RML spec

### ISSUE THREAD

**Issue by ghxiao** [oeg-upm/morph-rdb#13]
Hi, 

A quick comment. In the description of the project.
![screenshot 2015-01-14 15 43 30](https://cloud.githubusercontent.com/assets/1907371/5740485/1fc59cde-9c04-11e4-92dd-d5d5ae326bd6.png)

The link http://www.w3.org/2001/sw/rdb2rdf/r2rml/ is to the draft version of R2RML. I guess you want to link it to the latest R2RML spec: http://www.w3.org/TR/r2rml/ :-)

**Comment by fpriyatna** [comment]
Thanks a lot for the suggestion, done :D
