### ISSUE TITLE
mapping generation does'nt work

### ISSUE THREAD

**Issue by jerger** [oeg-upm/morph-rdb#17]
Hi,

I tryed out your installation description at https://github.com/oeg-upm/morph-rdb/wiki.
But unfortunately generation of mappings does'nt work for me

cmd, I use is:
"java -cp .:morph.jar:lib/\* es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner . morph.properties"

properties content is:
no_of_database=1
database.name[0]=xxx
database.driver[0]=com.mysql.jdbc.Driver
database.url[0]=jdbc:mysql://127.0.0.1:3306/
database.user[0]=xxx
database.pwd[0]=xxx
database.type[0]=mysql

I get the following exception:

Generating R2RML Mappings ...
es.upm.fi.dia.oeg.morph.r2rml.rdb.mappingsgenerator.exception.R2RMLException: Critical error in database schema.
        at es.upm.fi.dia.oeg.morph.r2rml.rdb.mappingsgenerator.control.R2RMLProcess.R2RMLBuild(R2RMLProcess.java:535)
        at es.upm.fi.dia.oeg.morph.r2rml.rdb.mappingsgenerator.main.R2RMLMapper.run(R2RMLMapper.java:238)
        at es.upm.fi.dia.oeg.morph.base.engine.MorphBaseRunnerFactory.createRunner(MorphBaseRunnerFactory.scala:51)

Do you have any idea?

Best regards,
Michael

**Comment by fpriyatna** [comment]
Thank you for reporting this issue. 

Have you tried the mapping generator with the examples? Are the examples not working, or just your particular database schema? If so, would it be possible to send us your database schema, so we can work on it? 

There are also log files in the active directory, it could be useful if you can also send us those log files.

Regards

**Comment by jerger** [comment]
Hi thanks for the fast answer :-)

I test on a real database not on examples. Unfortunately this database is foreign IP, so I can't provide a dump. Maybe I can provide the structure ... I will ask and come bak in about one week if you're interessed in.

The log file u mentioned I found. There are no errors in there and the logfile finishes with 

```
....
Table: TBLWIDGETNOTEPAD
    (No foreign keys)

    Fields:
        ID  INT  PRIMARY KEY
        WidgetName  VARCHAR  
        UserID  BIGINT  
        CreationDate  DATE  
        Title  VARCHAR  
        Text  VARCHAR  
        Priority  ENUM  
        Valid  ENUM  
        ValidFrom  DATE  
        ValidUntil  DATE  
        Category  VARCHAR  
        Path  VARCHAR  
        ParentID  BIGINT  
        IsFolder  TINYINT  
        Icon  VARCHAR  
        Catfields  LONGTEXT  

** Statistics: xxx
Tables: 93
Constraints: 0

** End of analysis for schema: xxx
```

The only remarable thing I found is the (No foreign keys) part ...
Is there sth like a debug switch?

Best Regards

**Comment by fpriyatna** [comment]
Can you tell us what database are you using?

**Comment by jerger** [comment]
Shure, I use MySql:
mysql  Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3

**Comment by fpriyatna** [comment]
Hmm, the mapping generator should work with MySQL.

Yes, we can wait for you to provide us the structure of the database, 
that will definitely help us solving this issue.

Thanks

**Comment by dachafra** [comment]
Not received the structure of the database for 5 years, issue closed 
We recommend creating mappings manually with yarrrml and export them as r2rml: https://rml.io/yarrrml/matey/
