### ISSUE TITLE
Error(?) in blank nodes management in SPARQL query result set

### ISSUE THREAD

**Issue by frmichel** [oeg-upm/morph-rdb#18]
Hi guys,
Just a minor one: in MorphXMLQueryResultWriter.process:
    val termTypeElementName = {
        if(termType.equalsIgnoreCase(Constants.R2RML_IRI_URI)) {
            "uri";
        } else if(termType.equalsIgnoreCase(Constants.R2RML_LITERAL_URI)) {
            "literal";
        } else {
            null
        }

I guess the null case is when the variable corresponds to a blank node. That may be weird to project a variable with a blank node value, but still when this happens you'll probably get a null pointer exception in the next line.
    val termTypeElement = xmlDoc.createElement(termTypeElementName);

Cheers,
   Franck.

**Comment by dachafra** [comment]
Think that the bug is resolved from 2016
