### ISSUE TITLE
Percent Decoding in Query Translator

### ISSUE THREAD

**Issue by fpriyatna** [oeg-upm/morph-rdb#22]
[Reported by Franck Michel]

Query Translator does not take into account the percent decoded value when translating URIs.

Given a mapping: http://example.org/{COLUMN_NAME}", an URI http://example.org/Some%20Value is translated into "... WHERE COLUMN_NAME = "Some Value"

**Comment by dachafra** [comment]
To test if it is solved

**Comment by dachafra** [comment]
tested, and it isn't solved, so it is bug

**Comment by dachafra** [comment]
Please @jatoledo, ensure that the uris are encoded correctly before writing the output.

**Comment by dachafra** [comment]
As for now, the option to encode all the URI is defined in the properties file, so as to accommodate different need/requests that we have received. We will consider your request to include those encodings.
