### ISSUE TITLE
output file format

### ISSUE THREAD

**Issue by sparkji** [oeg-upm/morph-rdb#23]
Does Morph actually support multiple output file format? Whatever I set the 'output.rdflanguage'  with N-TRIPLE ,TURTLE or N3, the output file always is N-TRIPLE format. And when I set it to RDF/XML, the output file just output prefix lines, no any triples in it.  Could you explain a little bit?

**Comment by fpriyatna** [comment]
Thanks for reporting this, we'll check this issue.

Freddy

**Comment by fpriyatna** [comment]
hi, just want to let you know that the support for RDB/XML has been added to version 3.7.5?
https://github.com/oeg-upm/morph-rdb/releases/tag/v3.7.5

Thanks!

**Comment by dachafra** [comment]
issue solved
