### ISSUE TITLE
Uri encoding

### ISSUE THREAD

**Issue by netkuup** [oeg-upm/morph-rdb#25]
Hi,

I’m trying to encode some strange characters from the Uri. I want to encode the "´" symbol to "%C2%B4", but is not working:

uri.encode=(" "->"%20"),,(","->""),,("á"->"a"),,("é"->"e"),,("í"->"i"),,("ó"->"o"),,("ú"->"u"),,("ü"->"u"),,("ñ"->"n"),,("´"->"%C2%B4")

There is any option to encode all the uri characters automatically or I have to define all of them manually? There is a long list… http://www.w3schools.com/tags/ref_urlencode.asp

**Comment by fpriyatna** [comment]
Thank you for reporting this issue.

Could you please try again with the version 3.7.4.
- https://github.com/oeg-upm/morph-rdb/releases/download/v3.7.4/morph-rdb-dist-3.7.4.jar
- https://github.com/oeg-upm/morph-rdb/releases/download/v3.7.4/lib.zip

As for now, the option to encode all the URI is defined in the properties file, so as to accomodate different need/requests that we have received. We will consider your request to include those encodings.

**Comment by netkuup** [comment]
It works, thanks :D
