### ISSUE TITLE
Invalid link

### ISSUE THREAD

**Issue by gigialmo88** [oeg-upm/morph-rdb#26]
I am following the steps from the https://github.com/oeg-upm/morph-rdb/wiki page and I am at the part where I run a set of predefined R2RML mappings with MySQL and once I click on this link: 
https://github.com/oeg-upm/morph-rdb/raw/master/morph-examples/examples/morph_example.sql
for the SQL example file, it says Page Not Found. Do I need to have this file in order to connect to the database and generate the R2RML mappings? 

Thanks!

**Comment by fpriyatna** [comment]
Sorry for the trouble, the link has changed, it is now at: https://raw.githubusercontent.com/oeg-upm/morph-rdb/master/morph-examples/examples-mysql/morph_example.sql
