### ISSUE TITLE
Split properties file

### ISSUE THREAD

**Issue by rgcmme** [oeg-upm/morph-rdb#3]
Right now the property file includes configurations:
- That usually do not change (e.g., the database configuration)
- That change every time the program is run (e.g., the mapping document, output file)

These two types of information should be in different configuration files.

For example, for running all the examples the database configuration has to be updated in every file with the same data. And for creating a new example the database configuration has to be included, even if it is always the same.

**Comment by dachafra** [comment]
closed as it is similar to #4
