### ISSUE TITLE
Morph-rdb on Windows for MSSQL db

### ISSUE THREAD

**Issue by priya-gitTest** [oeg-upm/morph-rdb#33]
Hi All

Has anyone tried to run Morph-rdb on windows with connection to MS SQL server for query re-writes, then kindly share the info.

From this https://github.com/oeg-upm/morph-rdb/wiki/Manual-Installation, its not clear how/what to run to generate R2ML mappings and how to run them.

Thanks

**Comment by priya-gitTest** [comment]
Also, whats the URL of the Sparql Endpoint ?

**Comment by dachafra** [comment]
no answer after one moth, issue closed
