### ISSUE TITLE
Error: Could not find or load main class es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner

### ISSUE THREAD

**Issue by joedavid91** [oeg-upm/morph-rdb#44]
Hi, I cannot get the examples to work and it gives the following error on running the batch file: Error: Could not find or load main class es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner

my batch file is untouched and looks like this:

cd ..

java -cp morph-rdb.jar;lib/* es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner examples-mysql example1-batch-mysql.morph.properties 

cd examples-mysql

I followed the manual installation for morph-RDB, for windows. I am quite certain that I have followed all the steps as it is quite straightforward.

**Comment by jatoledo** [comment]
Hi,

I understand that you have the configuration of the database made, being so try to modify the executable file with this:

cd ..

java -cp morph-rdb.jar;dependency/* es.upm.fi.dia.oeg.morph.r2rml.rdb.engine.MorphRDBRunner examples-mysql example1-batch-mysql.morph.properties

cd examples-mysql

regards.

**Comment by joedavid91** [comment]
Hi this works, thank you :)
