### ISSUE TITLE
Reference to null record created by rr:parentTriplesMap when the foreign key is null

### ISSUE THREAD

**Issue by ailintom** [oeg-upm/morph-rdb#46]
Dear developers of morph-rdb,
many thanks for a great tool. 

I have a problem with morph-rdb, which is creating references to null records when the foreign index is null. 
Suppose I have two mysql tables: 
foo
---
| foo_id | foo | boo | 
| ---: | --- | --- | 
| 2 | aa | bb | 
| 3 | cc | NULL | 

boo
---
| boo_id | boo | 
| ---: | --- | 
| 2 | bb | 
| 3 | dd | 
 

and I have a R2RML file: 

```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix ex: <https://test.de/ontology#>.
<#boo_map>
    rr:logicalTable [ rr:tableName "boo" ];
	   rr:subjectMap [
        rr:template "https://test.de/boo/{boo_id}";
        ];
	    rr:predicateObjectMap [
        rr:predicate ex:boo;
        rr:objectMap [ rr:column "boo" ;];].    
<#foo_map>
    rr:logicalTable [ rr:tableName "foo" ];
	   rr:subjectMap [
        rr:template "https://test.de/foo/{foo_id}";
        ];
	    rr:predicateObjectMap [
        rr:predicate ex:foo;
        rr:objectMap [ rr:column "foo" ;]		;
    ];
			   	    rr:predicateObjectMap [
        rr:predicate ex:has_boo;
		        rr:objectMap [
        rr:parentTriplesMap <#boo_map>;
        rr:joinCondition [
            rr:child "boo";
            rr:parent "boo";
        ];
           ];].
```

which results in the following RDF: 

```
<https://test.de/boo/2>	<https://test.de/ontology#boo>	"bb" .
<https://test.de/boo/3>	<https://test.de/ontology#boo>	"dd" .
<https://test.de/foo/2>	<https://test.de/ontology#has_boo>	<https://test.de/boo/2> .
<https://test.de/foo/2>	<https://test.de/ontology#foo>	"aa" .
<https://test.de/foo/3>	<https://test.de/ontology#has_boo>	<https://test.de/boo/null> .
<https://test.de/foo/3>	<https://test.de/ontology#foo>	"cc" .


```

The line `<https://test.de/foo/3>	<https://test.de/ontology#has_boo>	<https://test.de/boo/null> .` is an error on the side of morph-rdb, it should not include a non-existent null record from boo when the foreign key in foo has a null value. And other R2RML convertors don't generate this line.
Could you please correct this issue.

**Comment by fpriyatna** [comment]
Thank you for pointing out the issue. You are right, it should not generate /null. I will fix it.

Regards
Freddy

**Comment by fpriyatna** [comment]
Hi,

I have just fixed the issue with the release. Thanks again for pointing the issue out.

Regards
Freddy

**Comment by ailintom** [comment]
Hi,

Many thanks. Works great!

All the best 
Alexander
