### ISSUE TITLE
❓ Optional `predicateObjectMap` if template's parameters are not NULL

### ISSUE THREAD

**Issue by sroze** [oeg-upm/morph-rdb#58]
**Example table**
| foo | bar |
|-----|-----|
| sam |     |
| bob | key |

**R2RML configuration**
```
<#MyMap>
    rr:logicalTable [ rr:tableName "my_table ];
    rr:subjectMap [ rr:template "https://example.com/{foo}" ];

   rr:predicateObjectMap [
       rr:predicate <https://example.com/schema#myPredicate>;
       rr:objectMap [ rr:template "https://example.com/{foo}/{bar}" ];
   ];
.
```

**Question**
I would like to create this object map only if `bar` is not NULL. Typically, the above would only generate the following triple:
```
<https://example.com/bob> <https://example.com/schema#myPredicate <https://example.com/bob/key>
```

At the moment, it generates the following triple which I don't want:
```
<https://example.com/sam> <https://example.com/schema#myPredicate <https://example.com/sam/>
```

**Note:** I, however, would like to keep all the other `predicateObjectMap`s not relying on `bar`. Any idea on how to do so?

Thank you very much!

**Comment by dachafra** [comment]
Hi, you are right, following the R2RML specification, it says:
```
A term map is a function that generates an RDF term from a logical table row. The result of that function can be:

Empty – if any of the referenced columns of the term map has a NULL value,
...
```
So the complete object in the case has to be empty, hence, the triple shouldn't be generated.
@jatoledo @ArenasGuerreroJulian please take care of this bug

**Comment by ArenasGuerreroJulian** [comment]
Hi @sroze I have opened a PR that should resolve this issue. I have tested it with your data and your mappings.

**Comment by sroze** [comment]
Wonderful, thank you @ArenasGuerreroJulian. No tests? 😉
