### ISSUE TITLE
Generation of duplicates in batch mode

### ISSUE THREAD

**Issue by ArenasGuerreroJulian** [oeg-upm/morph-rdb#62]
Morph batch mode generates duplicates, even when  using `materialization.distinct=True`.

Current behaviour of materialization mode of Morph builds a sql query per each triples map and brings the data to memory. Triples are then generated by iterating over the rows of the in-memory table. One of the drawbacks of this strategy is the generation of duplicates, even when including the DISTINCT clause in the sql queries. This is because the DISTINCT is not applied in subject map or POM level, but at entire triples map level. Example:

![Screenshot from 2020-11-05 15-45-34](https://user-images.githubusercontent.com/18464038/98296182-d732c300-1fb2-11eb-92b0-62b29f86ef56.png)

This table is retrieved to generate the triples for one triples map. All rows are DISTINCT, but when morph process subjectMap (using trip_id) duplicates are generated because there are rows with repeated values in trip_id. Same logic applies when processing POMs.

**Comment by dachafra** [comment]
we are not going to cover materialization for the next version
